Add TypeScript module support
ronkok/Temml pull request #28
Opened 2023-08-11 11:14 UTC by ntsd

Add TypeScript support

Please rebuild (npm run build) and dist (npm run dist) again.

Example use

```ts
import temml, { type Options } from 'temml';

const tex = "c = \\pm\\sqrt{a^2 + b^2}";
const temmlOptions: Options = {};
temml.renderToString(tex, temmlOptions);
```

more example: https://github.com/ntsd/svelte-tex/blob/main/src/lib/MathML.svelte

2023-09-29 04:03 UTC, Trildar commented on package.json
> +      "import": "./dist/temml.cjs",
I think this should point to the `mjs` file as `import` typically implies ESM or at least some build system that can handle ESM.

2023-10-03 21:12 UTC, ronkok requested changes
@ntsd, Thank you for this PR. I don't know a lot about TypeScript and I am grateful for the help. Also, thank you for using the JSDoc comments. I find that to be much superior to inline type syntax.

I've made a couple of comments. When they are picked up, this should be ready to go.

2023-10-03 21:12 UTC, ronkok commented on dist/temml.d.ts
> +  wrap?: "tex" | "=";
Please revise to `wrap?: "tex" | "=" | "none";` 

`none` is a valid value. I'll update the documentation in the next release.

2023-10-03 21:12 UTC, ronkok commented on temml.d.ts
> +  wrap?: "tex" | "=";
Again, please revise to `wrap?: "tex" | "=" | "none";`

2023-10-04 05:10 UTC, ntsd commented
@ronkok, I did update the wrap type and defined the export functions type (still have `any` type but should have no problem).

Also, the commit includes JSDoc on the dist folder.

I am using Temmel on this module https://github.com/ntsd/svelte-tex the type is working fine.

2023-10-04 15:34 UTC, ronkok commented
Looks good to me. Thank you, @ntsd  and @Trildar.

2023-10-04 15:34 UTC, merged